In [1]:
import numpy as np

# 1. Write a NumPy program to test whether none of the elements of a given array is zero.

In [42]:
zero_array = np.array([2, 1, 0, 3])
non_zeros_array = np.array([1, 2, 3, 4])
flag = True

for ele in non_zeros_array:
    if ele == 0 :
        flag = True
    else :
        flag = False

if flag :
    print ("There is a zero among us")
else :
    print("There is no zero among us")



There is no zero among us


# 2. Write a NumPy program to test whether any of the elements of a given array is non-zero.

In [41]:
z = np.array([2,0,0,0])
a = np.array([0,0,0,0])

for ele in z:
    if ele == 0 :
        flag = True
    else :
        flag = False

if flag :
    print ("There is an integer among us")
else :
    print("There is only zeros among us")

There is an integer among us


# 3. Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given

# 4. Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.

In [46]:
zer0 = np.zeros(11)
zer0

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [47]:
one1s = np.ones(11)
one1s

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [49]:
fi5es = np.ones(11)*5
fi5es

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

# 5. Write a NumPy program to create an array of the integers from 30 to70.

In [54]:
ints = np.arange(30,71)
ints

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

In [64]:
from numpy import matlib as mat

# 6. Write a NumPy program to create a 3x3 identity matrix 7.

In [65]:
mat1 = mat.ones((3,3))*7
mat1

matrix([[7., 7., 7.],
        [7., 7., 7.],
        [7., 7., 7.]])

# 7. Write a NumPy program to generate a random number between 0 and 1

In [90]:
rando = np.random.randint(0,2)
rando

0

# 8. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution

In [95]:
ints2 = np.random.normal(0,100,15)
ints2

array([  55.13777527,  -17.22744067,  -24.9985952 , -170.54492208,
         72.59601639,  -98.94745833,  -43.18922856,    6.00440841,
        -22.05837313,  -62.40755631, -112.04900602,  160.57250709,
        -53.82797628,   26.59371534,   57.04569213])

# 9. Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.