In [47]:
import numpy as np

# 1. Write a NumPy program to test whether none of the elements of a given array is zero.

In [48]:
zero_array = np.array([2, 1, 0, 3])
non_zeros_array = np.array([1, 2, 3, 4])
flag = True

for ele in non_zeros_array:
    if ele == 0 :
        flag = True
    else :
        flag = False

if flag :
    print ("There is a zero among us")
else :
    print("There is no zero among us")



There is no zero among us


# 2. Write a NumPy program to test whether any of the elements of a given array is non-zero.

In [49]:
z = np.array([2,0,0,0])
a = np.array([0,0,0,0])

for ele in z:
    if ele == 0 :
        flag = True
    else :
        flag = False

if flag :
    print ("There is an integer among us")
else :
    print("There is only zeros among us")

There is an integer among us


# 3. Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given

In [50]:
array1 = np.array([1,2,3,4,5,6])
array2 = np.array([6,5,4,3,2,1])
sum_ = []
for i in array1:
    for m in array2:
        if m == i :
            flag = "The 2 arrays are identical"
        else :
            flag = "The 2 arrays are not identical"

flag

'The 2 arrays are not identical'

# 4. Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.

In [51]:
zer0 = np.zeros(11)
zer0

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [52]:
one1s = np.ones(11)
one1s

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [53]:
fi5es = np.ones(11)*5
fi5es

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

# 5. Write a NumPy program to create an array of the integers from 30 to70.

In [54]:
ints = np.arange(30,71)
ints

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

In [55]:
from numpy import matlib as mat

# 6. Write a NumPy program to create a 3x3 identity matrix 7.

In [56]:
mat1 = mat.ones((3,3))*7
mat1

matrix([[7., 7., 7.],
        [7., 7., 7.],
        [7., 7., 7.]])

# 7. Write a NumPy program to generate a random number between 0 and 1

In [57]:
rando = np.random.randint(0,2)
rando

1

# 8. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution

In [58]:
ints2 = np.random.normal(0,100,15)
ints2

array([ -65.79708995,   42.21130617,   62.40233379,   50.16400965,
         84.14347266, -164.02499842,  105.80051586,   -9.17844425,
        -72.40345933,  -40.04603572,   44.53245845,   95.9939649 ,
       -134.63538403,  201.88993741,  108.23763468])

# 9. Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.

In [59]:
inttt = np.arange(15,56)
inttt[1:-1]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54])

# 10. Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10

In [60]:
rand0 = np.arange(0,10,2)
rand0

array([0, 2, 4, 6, 8])

# 11. Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.

In [61]:
border = np.ones((10,10))
border[1:-1, 1:-1] = 0
border

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

# 12. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [62]:
diag = np.diag([1,2,3,4,5])
diag

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

# 13. Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal.

In [63]:
stag = np.zeros((4, 4))
stag[::2, 1::2] = 1
stag[1::2, ::2] = 1
stag

array([[0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]])

# 14. Write a NumPy program to save two given arrays into a single file in compressed format (.npz format) and load it.

# 15. Write a NumPy program to create a one dimensional array of forty pseudo-randomly generated values. Select

In [64]:
np.random.seed(10)
rand_40 = np.random.rand(40)
rand_40

array([0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701,
       0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981,
       0.68535982, 0.95339335, 0.00394827, 0.51219226, 0.81262096,
       0.61252607, 0.72175532, 0.29187607, 0.91777412, 0.71457578,
       0.54254437, 0.14217005, 0.37334076, 0.67413362, 0.44183317,
       0.43401399, 0.61776698, 0.51313824, 0.65039718, 0.60103895,
       0.8052232 , 0.52164715, 0.90864888, 0.31923609, 0.09045935,
       0.30070006, 0.11398436, 0.82868133, 0.04689632, 0.62628715])

# 16. Write a NumPy program to extract all numbers from a given array which are less and greater than a specified number.

In [65]:
itr = np.array([1,5,4,6,2,3,9,7])
ext = []
for i in itr:
    if i > 5:
       ext.append(i)
ext

[6, 9, 7]